- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: webservers
  become: true

  tasks:
    - name: Import Datadog Agent role
      import_role:
        name: datadog.dd.agent
